# Generated by Django 5.2.9 on 2025-12-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication_LTD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
