# Generated by Django 5.2.9 on 2025-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Communication_LTD', '0002_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='code_hash',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='resetcode',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
